// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.example.tutorial.addressbook

object AddressbookProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.timestamp.TimestampProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.example.tutorial.addressbook.Person,
      com.example.tutorial.addressbook.AddressBook
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChZ0ZXN0L2FkZHJlc3Nib29rLnByb3RvEgh0dXRvcmlhbBofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byKSAwoGU
  GVyc29uEh0KBG5hbWUYASABKAlCCeI/BhIEbmFtZVIEbmFtZRIXCgJpZBgCIAEoBUIH4j8EEgJpZFICaWQSIAoFZW1haWwYAyABK
  AlCCuI/BxIFZW1haWxSBWVtYWlsEkEKBnBob25lcxgEIAMoCzIcLnR1dG9yaWFsLlBlcnNvbi5QaG9uZU51bWJlckIL4j8IEgZwa
  G9uZXNSBnBob25lcxJPCgxsYXN0X3VwZGF0ZWQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQhDiPw0SC2xhc3RVc
  GRhdGVkUgtsYXN0VXBkYXRlZBptCgtQaG9uZU51bWJlchIjCgZudW1iZXIYASABKAlCC+I/CBIGbnVtYmVyUgZudW1iZXISOQoEd
  HlwZRgCIAEoDjIaLnR1dG9yaWFsLlBlcnNvbi5QaG9uZVR5cGVCCeI/BhIEdHlwZVIEdHlwZSIrCglQaG9uZVR5cGUSCgoGTU9CS
  UxFEAASCAoESE9NRRABEggKBFdPUksQAiJECgtBZGRyZXNzQm9vaxI1CgZwZW9wbGUYASADKAsyEC50dXRvcmlhbC5QZXJzb25CC
  +I/CBIGcGVvcGxlUgZwZW9wbGVCUAoUY29tLmV4YW1wbGUudHV0b3JpYWxCEUFkZHJlc3NCb29rUHJvdG9zqgIkR29vZ2xlLlByb
  3RvYnVmLkV4YW1wbGVzLkFkZHJlc3NCb29rYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}