// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.example.tutorial.addressbook

/** Our address book file is just one of these.
  */
@SerialVersionUID(0L)
final case class AddressBook(
    people: _root_.scala.Seq[com.example.tutorial.addressbook.Person] = _root_.scala.Seq.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[AddressBook] with scalapb.lenses.Updatable[AddressBook] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      people.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      people.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.example.tutorial.addressbook.AddressBook = {
      val __people = (_root_.scala.collection.immutable.Vector.newBuilder[com.example.tutorial.addressbook.Person] ++= this.people)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __people += _root_.scalapb.LiteParser.readMessage(_input__, com.example.tutorial.addressbook.Person.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      com.example.tutorial.addressbook.AddressBook(
          people = __people.result()
      )
    }
    def clearPeople = copy(people = _root_.scala.Seq.empty)
    def addPeople(__vs: com.example.tutorial.addressbook.Person*): AddressBook = addAllPeople(__vs)
    def addAllPeople(__vs: Iterable[com.example.tutorial.addressbook.Person]): AddressBook = copy(people = people ++ __vs)
    def withPeople(__v: _root_.scala.Seq[com.example.tutorial.addressbook.Person]): AddressBook = copy(people = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => people
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(people.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.example.tutorial.addressbook.AddressBook
}

object AddressBook extends scalapb.GeneratedMessageCompanion[com.example.tutorial.addressbook.AddressBook] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.example.tutorial.addressbook.AddressBook] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): com.example.tutorial.addressbook.AddressBook = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.example.tutorial.addressbook.AddressBook(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.Seq[com.example.tutorial.addressbook.Person]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.example.tutorial.addressbook.AddressBook] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.example.tutorial.addressbook.AddressBook(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[com.example.tutorial.addressbook.Person]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AddressbookProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AddressbookProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.example.tutorial.addressbook.Person
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.example.tutorial.addressbook.AddressBook(
    people = _root_.scala.Seq.empty
  )
  implicit class AddressBookLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.example.tutorial.addressbook.AddressBook]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.example.tutorial.addressbook.AddressBook](_l) {
    def people: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[com.example.tutorial.addressbook.Person]] = field(_.people)((c_, f_) => c_.copy(people = f_))
  }
  final val PEOPLE_FIELD_NUMBER = 1
  def of(
    people: _root_.scala.Seq[com.example.tutorial.addressbook.Person]
  ): _root_.com.example.tutorial.addressbook.AddressBook = _root_.com.example.tutorial.addressbook.AddressBook(
    people
  )
}
