name: Test
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build image
      run: make image
    - name: Test code generation
      run: make test
